//import
import { addLog, initializeLog } from './log-function';
import {
  APIGatewayClient,
  GetRestApisCommand,
  DeleteRestApiCommand,
} from '@aws-sdk/client-api-gateway';
import { deleteShipsTable } from './dynamodb-operations';
import { deleteAllProjectBuckets } from './s3-function';


const apiGatewayClient = new APIGatewayClient({
  region: 'eu-west-1',
});

const API_NAME = 's3-content-api-boat';

// Log file path
const LOG_FILE = './destroy.log';

async function deleteProjectApiGateways(logFile = LOG_FILE) {
  addLog('🔍 Looking for project API Gateway instances...', logFile);

  let position: string | undefined;
  const apisToDelete: string[] = [];

  do {
    const result = await apiGatewayClient.send(
      new GetRestApisCommand({ position, limit: 500 })
    );

    for (const api of result.items ?? []) {
      if (api.name === API_NAME && api.id) {
        apisToDelete.push(api.id);
      }
    }

    position = result.position;
  } while (position);

  if (apisToDelete.length === 0) {
    addLog(`ℹ️ No API Gateway found with name "${API_NAME}"`, logFile);
    return;
  }

  for (const restApiId of apisToDelete) {
    await apiGatewayClient.send(new DeleteRestApiCommand({ restApiId }));
    addLog(`✅ API Gateway deleted: ${restApiId}`, logFile);
  }
}

// Main function to execute destructive operation
async function main() {
  try {
    initializeLog(LOG_FILE);
    addLog('🚀 Starting Project Deletion...', LOG_FILE);

    // Delete all S3 ressources
    await deleteAllProjectBuckets(LOG_FILE);

    // Delete DynamoDB table
    await deleteShipsTable();

    // Delete API Gateway REST APIs generated by the project
    await deleteProjectApiGateways(LOG_FILE);

    addLog('\n✅ Project deleted successfully...', LOG_FILE);
  } catch (error) {
    addLog('❌ Error: ' + error, LOG_FILE);
  }
}

// Execute the main function
main();

// Export to make this a module and avoid global scope conflicts
export { };